# 조건:
# 1. 2021년에 가입한 전체 회원들(USER_INFO 에서 JOINED LIKE '%2021')
# 2. 상품 구매한 회원수(ONLINE_SALE에서의 USER_ID) / 상품 구매한 회원 비율 (2021 가입 중 구매 회원수 / 전체 2021 가입자)
# 3. 년, 월 별 (GROUP BY YEAR, MONTH)
# 전체 유저: USER_INFO에서 COUNT(USER_ID)
# 구매한 유저: ONLINE_SALE에서 COUNT(DISTINCT USER_ID)

SELECT
YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021-%'), 1) AS PURCHASED_RATIO

FROM USER_INFO I
JOIN ONLINE_SALE S
USING(USER_ID)
WHERE JOINED LIKE '2021-%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH