-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소, 
    CONCAT_WS('-', SUBSTR(TLNO,1,3), SUBSTR(TLNO,4,4), SUBSTR(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(B.USER_ID) >= 3
ORDER BY A.WRITER_ID DESC