SELECT MEM.MEMBER_NAME, REV.REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MEM
JOIN (
    SELECT *
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(*) = (
            SELECT COUNT(*)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC LIMIT 1
        )
    )
) REV
ON MEM.MEMBER_ID = REV.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT