# SELECT HISTORY_ID, SUM(DATEDIFF(END_DATE, START_DATE)+1) AS DIFF
# CASE
# WHEN DIFF
# FROM CAR_RENTAL_COMPANY_CAR CAR
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
# ON CAR.CAR_ID = HISTORY.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
# ON CAR.CAR_TYPE = PLAN.CAR_TYPE
# WHERE CAR.CAR_TYPE = '트럭'
# GROUP BY HISTORY_ID

SELECT HISTORY_ID, ROUND((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE * (
    100 - (
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
            THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
            THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
            THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')
            ELSE 0
        END
    )
) * 0.01, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC